---
apiVersion: v1
kind: Service
metadata:
  name: elastic-apm-java-injector
  labels:
    app: elastic-apm-java-injector
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: elastic-apm-java-injector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-apm-java-injector
  labels:
    app: elastic-apm-java-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-apm-java-injector
  template:
    metadata:
      name: elastic-apm-java-injector
      labels:
        app: elastic-apm-java-injector
    spec:
      containers:
      - name: elastic-apm-java-injector
        image: local/elastic-apm-java-injector:latest
        imagePullPolicy: Never
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "test app"
        volumeMounts:
        - name: ssl
          mountPath: "/ssl"
          readOnly: true
        resources:
          limits:
            cpu: 250m
            memory: 64Mi
          requests:
            cpu: 250m
            memory: 64Mi
      volumes:
      - name: ssl
        secret:
          secretName: elastic-apm-java-injector-certs
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: elastic-apm-java-injector
  labels:
    app: elastic-apm-java-injector
webhooks:
  - name: elastic-apm-java-injector.default.svc.cluster.local
    clientConfig:
      caBundle: CA_BUNDLE
      service:
        name: elastic-apm-java-injector
        namespace: default
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        elastic-apm-java-injector: enabled
